
target 'osx-app', :exclusive => true do
  	platform :osx, '10.11'
	pod 'handlebars-objc', :path => "../../../../"
end

target 'ios-app', :exclusive => true do
  	platform :ios, '9.0'
  	pod 'handlebars-objc', :path => "../../../../"
end
