
target 'osx-app', :exclusive => true do
  	platform :osx, '10.8'
	pod 'handlebars-objc', :path => "../../../../"
end

target 'ios-app', :exclusive => true do
  	platform :ios, '6.0'
  	pod 'handlebars-objc', :path => "../../../../"
end